### ISSUE TITLE
Cluster 1 of plot does not show; all the terms (7) do not show on the other Clusters

### ISSUE THREAD

**Issue by ghost** [juba/rainette#12]
I wrote directly before, you corrected the problem, but this one remains.  My same file that I sent would be applicable.
<img width="278" alt="Screenshot 2022-03-17 110354" src="https://user-images.githubusercontent.com/7195528/158832930-9306d30c-8422-4352-b12b-d54e0c6fad3d.png">

**Comment by juba** [comment]
I think the fact that the plot for the first cluster is empty is due to the fact that it is a very small group of only two documents, so there is no feature for which the keyness statistics is significant. Same thing for the fifth topic, there may be only 3 statistically significant features keyness.

You may check this by computing keyness directly with something like this : 

```r
groups <- cutree(rainClus, k = 6)
quanteda.textstats::textstat_keyness(rainDFM, target = groups == 1, measure = "chi2")
```

This should not show any feature with a p-value lesser than 0.05.
