### ISSUE TITLE
Time series analysis

### ISSUE THREAD

**Issue by gabrielparriaux** [juba/rainette#24]
Hello,

Is it possible to do time series analysis with the data coming from `rainette`?

I have seen these kinds of graphs that are very interesting when you want to see the evolution of clusters during the time.

<img width="1179" alt="Capture d’écran 2023-01-30 à 10 15 34" src="https://user-images.githubusercontent.com/125275/215439079-81ed1ffa-026e-4ab0-8065-c16a822c9c30.png">

<img width="1179" alt="Capture d’écran 2023-01-30 à 10 15 47" src="https://user-images.githubusercontent.com/125275/215439111-ec9a3d3f-a990-4929-8057-86d775c5111f.png">

(source: Manchaiah, V., Ratinaud, P., & Andersson, G. (2018). Representation of tinnitus in the US newspaper media and in Facebook pages : Cross-sectional analysis of secondary data. _Interactive Journal of Medical Research_, 7(1), e9065.)

Two questions about that:

— to obtain a similar graph, do you know if you need to conduct separate clustering operations, splitting the corpus by year and performing a new `rainette` clustering for each year? Or can you take the whole corpus together and do one big clustering, the result of which would be then be split by years?

— do you have an idea of the way to obtain something similar with the data provided by `rainette`?

Thanks a lot for helping!

**Comment by juba** [comment]
I think you would have to run the clustering on the whole dataset, otherwise if you run it year by year you won't necessarily obtain comparable clusters. 

To produce this type of analysis, you first need to have a date information about your documents in your corpus metadata. After clustering the documents with rainette, you can use `cutree` to add a new variable to your metadata containing each document cluster. Then you can easily use both the cluster and date variables to generate plots or other analyses about evolution of clusters along time for example.

**Comment by gabrielparriaux** [comment]
Thanks a lot for your advice on this topic! Any hint about where to start with the code to plot such a graph?

**Comment by juba** [comment]
It really depends on what you want to plot... May be you could take a look at `mosaicplot` or, if you use ggplot2, you can use something like `geom_col` with `position=fill`.

**Comment by gabrielparriaux** [comment]
Sounds great! Thanks a lot for pointing to this! I will check it out!
